### ISSUE TITLE
The game just crashed whenever I try to have some fall damage (latest package update).

### ISSUE THREAD

**Issue by minhcrafters** [nanos-world/nanos-world-sandbox#17]
![image](https://user-images.githubusercontent.com/59521026/221353311-834eb5d0-8c9d-49c1-9a05-83913dada6e2.png)

**Comment by vugi99** [comment]
Nice catch but this should be reported on [nanos issue tracker](https://github.com/nanos-world/issues/issues) as this is a game issue.
I'll do it for you

**Comment by minhcrafters** [comment]
oh, I didn't know that
thanks for doing it for me

**Comment by gtnardy** [comment]
Thanks for reporting! Closing this as this was fixed in the other issue.
