### ISSUE TITLE
Physics gun minimum position set to camera

### ISSUE THREAD

**Issue by sam-nx** [nanos-world/nanos-world-sandbox#18]
The Physics gun minimum position (when you scroll to move the object you carry) is not set to the player position but to the camera position
[nanos.world   2023-03-16 19-42-03 - Trim.zip](https://github.com/nanos-world/nanos-world-sandbox/files/10994833/nanos.world.2023-03-16.19-42-03.-.Trim.zip)

**Comment by gtnardy** [comment]
yeah I suffered from that effect too, I will try to improve it in the Physics Gun tool implementation!
