### ISSUE TITLE
Doesnt change color for all models

### ISSUE THREAD

**Issue by donald-mason23** [nanos-world/nanos-world-sandbox#27]
Doesnt change color for all models
![model](https://github.com/nanos-world/nanos-world-sandbox/assets/141275050/fec38ab6-2b63-45e8-93e4-b754cccaabc6)
![model2](https://github.com/nanos-world/nanos-world-sandbox/assets/141275050/5d814f34-e846-4958-8d6d-b695f8c8cbcf)

**Comment by Timmy-the-nobody** [comment]
It's not really a bug, when hitting a target the color tool changes the "Tint" material color parameter of the entity, if the material doesn't support this parameter nothing will change

Maybe a new material tool could be usefull to change the material of an entity, so the color tool could work on any entity if a correct material is applied

**Comment by gtnardy** [comment]
I will edit those meshes materials to support Tint too, at least they get something changed then
