### ISSUE TITLE
Add the option to rotate the second angle of objects by using ALT without E

### ISSUE THREAD

**Issue by Sebihunter** [nanos-world/nanos-world-sandbox#3]
At the moment objects can not be properly rotated at all angles

**Comment by gtnardy** [comment]
Isn't this the ALT+E?

**Comment by Sebihunter** [comment]
Added the function in my fork https://github.com/Sebihunter/nanos-world-sandbox

**Comment by gtnardy** [comment]
Hello! Please make a pull request on the main repo ;)

**Comment by gtnardy** [comment]
That was added in the main project 😉
