### ISSUE TITLE
Always show keybinds needed for tools when having a specific toolgun selected

### ISSUE THREAD

**Issue by Sebihunter** [nanos-world/nanos-world-sandbox#4]
Only showing the tutorial once is from my point of view not enough because the keybinds differ a lot from each other with every toolgun. Always displaying the name of the selected toolgun + how to use it may help newcomers to the gamemode

**Comment by gtnardy** [comment]
This would be really a good thing!

**Comment by Sebihunter** [comment]
Added a basic version of that in my fork https://github.com/Sebihunter/nanos-world-sandbox
